# This image is intended for testing purposes, 
# it only should be used for testing
# 
FROM alpine:3.6

# Default to UTF-8 file.encoding
ENV LANG=C.UTF-8 \
 JAVA_VERSION=8u131 \ 
 JAVA_ALPINE_VERSION=8.131.11-r1 \
 JVM_OPTIONS="" \
 PORT_NUMBER=9090 \
 JAVA_PARAMS="0"
 
RUN set -x && \
	adduser beepbeep -D && \
	mkdir -p /opt/kaboom  && \
	mkdir -p /var/dump && \
  apk add --no-cache openjdk8="$JAVA_ALPINE_VERSION"

	
COPY ./src/main/java/KaboomServer.java /opt/kaboom
COPY ./src/main/dockerfiles/bash/coyote.sh /opt/kaboom

RUN chgrp beepbeep /opt/kaboom && \
  chmod -R g+rwX /opt/kaboom  && \
	chgrp beepbeep /var/dump && \
	chmod -R g+rwX /var/dump 

WORKDIR /opt/kaboom

RUN cd /opt/kaboom && \
   chmod a+x /opt/kaboom/coyote.sh && \
	/usr/lib/jvm/java-1.8-openjdk/bin/javac KaboomServer.java 

EXPOSE 9090
EXPOSE 2020

USER beepbeep

#ENTRYPOINT ["/bin/sh"]

CMD ["/opt/kaboom/coyote.sh"]
